### PR TITLE
Add new SCSS config

### PR DESCRIPTION
**Pull request by pascalduez**
Addresses #6

### CODE REVIEW

**Comment by fgblomqvist** [comment]
Since you already only support Stylelint 14 and up I would advice you to use `overrides` rather than split things into two files. It simplifies it for the end-consumer (only one path to import).

You can see an example here: https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/main/index.js

**Comment by pascalduez** [comment]
> Since you already only support Stylelint 14 and up I would advice you to use overrides rather than split things into two files. It simplifies it for the end-consumer (only one path to import).

This would force `.scss` files user to necessarily install `stylelint-config-recommended-scss` or `stylelint-scss`, which I'm not keen of. By having a separate file it gives more granularity.

**Comment by pascalduez** [comment]
Another option would be to set `stylelint-scss` as `optionalDependency` and explicitly state in the docs that they should use `--no-optional` while installing by default.    
Not necessarily the best either....

**Comment by fgblomqvist** [comment]
Hmm okay I see. So with the current setup the user would have to manually make sure the correct SCSS deps are installed for this package to work correctly?

**Comment by pascalduez** [comment]
> Hmm okay I see. So with the current setup the user would have to manually make sure the correct SCSS deps are installed for this package to work correctly?

Yes, as mentionned in the Readme. Gosh there's no good solution here.

Yet another solution, set `stylelint-scss` as peerDependency, Use overrides. But this means any user, even non SCSS users would have to install it otherwise they will get the missing peerDep warning.

**Comment by fgblomqvist** [comment]
With npm >=7 peerDeps are installed automatically in most cases. I don't see a way to solve this in a convenient manner sadly. The best solution, if the goal is to prevent people from having to install unnecessary packages, is probably to split the package into two packages (could still live in the same repo, monorepo style). I'm not sure what most packages do, but I suspect most of them just "force" these unnecessary deps on the users, out of simplicity. This package is just a devDep after all so it won't bloat people's bundles or anything like that.

**Comment by pascalduez** [comment]
> With npm >=7 peerDeps are installed automatically in most cases
Yeah true.

> split the package into two packages (could still live in the same repo, monorepo style)
A bit overkill for such small packages I guess.

>  I suspect most of them just "force" these unnecessary deps on the users, out of simplicity
Okay, let's go this way.

Thanks for your feedback!

**Comment by fgblomqvist** [comment]
No problem, and sounds good 🙂

**Pull request merged**
